include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
analyzer:
  errors:
    missing_return: error
    missing_required_param: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"